"use client";import{useState}from"react";
const services=[["01","Air Freight","General cargo, courier, dangerous goods, valuables, pharma and perishables."],["02","Sea Freight","FCL, LCL, reefer, hazardous cargo, RO-RO, OOG and project cargo."],["03","Land Freight","FTL, LTL, oversized goods, ADR and temperature-controlled transport."],["04","Warehousing","Storage, packaging, inventory management, distribution and cross docking."],["05","Project Logistics","Air / sea chartering, multimodal transport, break bulk and RO-RO."]];
export default function Home(){const[track,setTrack]=useState("");return <main>
<header className="nav"><div className="brand"><img src="/kas-logo.png" alt="KAS Logistics" style={{height:"38px", width:"auto"}} /><small>LOGISTICS</small></div><nav><a href="#services">Services</a><a href="#network">Network</a><a href="#technology">Technology</a><a href="#about">About</a></nav><button>Get a Quote</button></header>
<section className="hero"><div className="gridGlow"/><div className="heroCopy"><p className="eyebrow">KAS FOR LOGISTICS SERVICES · RIYADH</p><h1>MOVE WHAT<br/><em>MATTERS.</em></h1><p className="lead">End-to-end logistics connecting global supply chains with the Middle East & Africa.</p><div className="actions"><button>Start a Shipment ↗</button><a href="#services">Explore Services</a></div></div><div className="controlCard"><div className="cardTop"><span>KAS CONTROL TOWER</span><span className="live">● LIVE</span></div><div className="routeLine"><div><strong>GLOBAL</strong><small>ORIGIN</small></div><div className="route"><i/><i/><i/></div><div><strong>MENA / AFRICA</strong><small>DESTINATION</small></div></div><div className="stats"><div><b>24/7</b><span>VISIBILITY</span></div><div><b>05</b><span>CORE MODES</span></div><div><b>08+</b><span>NETWORK MARKETS</span></div></div></div></section>
<section className="tracking"><div><p className="eyebrow">SHIPMENT VISIBILITY</p><h2>Track anything.</h2><p>AWB · Container · PO · Shipment reference</p></div><div className="trackBox"><input value={track} onChange={e=>setTrack(e.target.value)} placeholder="Enter tracking number"/><button>Track Shipment →</button></div></section>
<section id="services" className="section"><div className="sectionHead"><p className="eyebrow">WHAT WE MOVE</p><h2>One logistics partner.<br/><em>Every critical mile.</em></h2></div><div className="serviceGrid">{services.map(([n,t,d])=><article className="service" key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p><a href="#">Discover ↗</a></article>)}</div></section>
<section id="technology" className="darkPanel"><div className="sectionHead"><p className="eyebrow">DIGITAL LOGISTICS</p><h2>A control tower for<br/><em>your supply chain.</em></h2><p className="muted">Built around visibility, digital operations, digital quoting, CRM and automated invoicing.</p></div><div className="dashboard"><div className="dashTop"><span>SHIPMENT CONTROL</span><span>ALL NETWORKS · LIVE</span></div><div className="dashMetrics"><div><small>IN TRANSIT</small><b>128</b></div><div><small>DELIVERED</small><b>842</b></div><div><small>AT RISK</small><b>07</b></div><div><small>ACTION REQUIRED</small><b>14</b></div></div><div className="map"><i/><i/><i/><i/><i/><i/></div></div></section>
<section id="network" className="network"><div><p className="eyebrow">THE KAS NETWORK</p><h2>Built to connect<br/><em>markets.</em></h2><p className="muted">Headquartered in Riyadh, with a network across the Middle East and Africa and worldwide affiliate partners.</p></div><div className="marketList"><div><b>Middle East</b><span>Saudi Arabia · UAE</span></div><div><b>Africa</b><span>Kenya · South Africa · Namibia · Sudan · Rwanda</span></div><div><b>Worldwide</b><span>Air · Sea · Land affiliate network</span></div></div></section>
<section id="about" className="about"><div className="bigNumber">2023</div><div><p className="eyebrow">KAS LOGISTICS</p><h2>Technology with<br/>human accountability.</h2><p>Founded in 2023 in Riyadh, KAS Logistics is built around end-to-end logistics solutions, sustainable growth and strong customer relationships.</p><button>About KAS →</button></div></section>
<footer><div className="brand"><b>KAS</b><small>LOGISTICS</small></div><div><b>CONNECT</b><p>info@kaslogistic.com<br/>sales@kaslogistic.com<br/>www.kaslogistic.com</p></div><div><b>NEXT</b><p>Customer Portal<br/>Digital Quote<br/>API Integration</p></div><div><b>© 2026 KAS</b><p>Riyadh, Saudi Arabia</p></div></footer>
</main>}
