"use client";
import {useState} from 'react';
const services=[['01','Air Freight','General cargo, courier, dangerous goods, valuables, pharma and perishables.','✈'],['02','Sea Freight','FCL, LCL, reefer, hazardous, RO-RO, OOG and project cargo.','⚓'],['03','Land Freight','FTL, LTL, oversized goods, ADR and temperature-controlled transport.','▰'],['04','Warehousing','Storage, labeling, packing, inventory, distribution and cross docking.','▦'],['05','Project Logistics','Chartering, multimodal, break bulk, RO-RO and complex cargo solutions.','◈'],['06','Digital Logistics','Live tracking, digital quotes, CRM, operations and automated invoicing.','⌁']];
const industries=['Industrial & Manufacturing','E-Commerce','Healthcare & Pharma','Automotive','Energy & Projects','Retail & Consumer','Perishables','Special Cargo'];
const network=['Saudi Arabia','UAE','Kenya','South Africa','Namibia','Sudan','Rwanda'];
export default function Home(){const [track,setTrack]=useState('');const [sent,setSent]=useState(false);const [menu,setMenu]=useState(false);return <main>
<header className="header"><a className="logo" href="#top"><img src="/kas-logo.png" alt="KAS Logistics Services"/></a><nav className={menu?'nav open':'nav'}>{['Services','Industries','Global Network','Digital Solutions','About KAS','Contact'].map(x=><a key={x} href={'#'+x.toLowerCase().replaceAll(' ','-')} onClick={()=>setMenu(false)}>{x}</a>)}</nav><div className="headRight"><span className="lang">EN⌄</span><a className="quote" href="#contact">Get a Quote ↗</a><button className="hamb" onClick={()=>setMenu(!menu)}>{menu?'×':'☰'}</button></div></header>
<section id="top" className="hero"><div className="heroArt"><div className="orb"/><div className="ship">▰▰▰</div><div className="route r1"/><div className="route r2"/><div className="route r3"/></div><div className="heroOverlay"/><div className="heroContent"><p className="eyebrow">LOGISTICS BEYOND BORDERS</p><h1>WE MOVE WHAT<br/><span>MOVES THE WORLD.</span></h1><p className="lead">End-to-end logistics connecting the Middle East, Africa and the world. Built around visibility, reliability and the way your business moves.</p><div className="actions"><a className="primary" href="#contact">Get a Quote →</a><a className="outline" href="#tracking">Track Shipment ↗</a></div></div><div className="stats"><div><b>2023</b><small>Founded in Riyadh</small></div><div><b>7+</b><small>Network Markets</small></div><div><b>MEA</b><small>Core Region</small></div><div><b>24/7</b><small>Operational Mindset</small></div></div></section>
<div className="ticker"><span>GLOBAL LOGISTICS</span><span>LOCAL EXPERTISE</span><span>RIYADH · GCC · MIDDLE EAST · AFRICA</span><span>ONE PARTNER. EVERY MOVE.</span></div>
<section id="services" className="section"><div className="intro"><div><p className="eyebrow dark">WHAT WE MOVE</p><h2>One supply chain.<br/><em>Every mode.</em></h2></div><p>From a single shipment to complex project cargo, KAS connects the right mode, route and operational expertise around your business.</p></div><div className="cards">{services.map(s=><article className="card" key={s[0]}><div className="cardTop"><span>{s[0]}</span><b>KAS</b></div><i>{s[3]}</i><h3>{s[1]}</h3><p>{s[2]}</p><a href="#contact">Explore service →</a></article>)}</div></section>
<section id="tracking" className="track"><div className="trackVisual"><div className="mapGrid"/><div className="live">KAS CONTROL TOWER <b>● LIVE</b></div><div className="dots"><i/><i/><i/><i/></div><div className="path pA"/><div className="path pB"/><div className="path pC"/><div className="routeLabels"><b>GLOBAL ORIGIN</b><strong>→</strong><b>MENA / AFRICA DESTINATION</b></div></div><div className="trackPanel"><p className="eyebrow dark">TRACK YOUR SHIPMENT</p><h2>Know where it is.<br/><em>Know what happens next.</em></h2><p>Enter your shipment reference to access the latest available movement status.</p><form onSubmit={e=>{e.preventDefault();if(track.trim())setSent(true)}}><input value={track} onChange={e=>setTrack(e.target.value)} placeholder="Enter tracking number"/><button>Track →</button></form>{sent&&<div className="result"><b>REFERENCE RECEIVED</b><span>{track}</span><small>Live status will appear here when connected to the KAS tracking system.</small></div>}<div className="timeline"><span>● Picked Up</span><span>○ In Transit</span><span>○ Customs</span><span>○ Delivered</span></div></div></section>
<section id="digital-solutions" className="dark"><div className="intro digitalIntro"><div><p className="eyebrow">KAS DIGITAL LOGISTICS ECOSYSTEM</p><h2>THE <em>CONTROL TOWER.</em><br/>FOR EVERY MOVE.</h2></div><p>Digital tools designed to turn logistics data into operational visibility and better decisions.</p></div><div className="dashboard"><div className="dashHead"><span>KAS CONTROL TOWER</span><b>● SYSTEM OPERATIONAL</b></div><div className="metrics">{[['SHIPMENT VISIBILITY','24 / 7','Real-time operational view'],['DIGITAL QUOTES','FAST','Rate requests in one workflow'],['OPERATIONS','ONE VIEW','CRM and shipment coordination'],['INVOICING','AUTO','Less friction, more control']].map(x=><div key={x[0]}><small>{x[0]}</small><strong>{x[1]}</strong><span>{x[2]}</span></div>)}</div><div className="dashRoute">RIYADH <b>────────●────────●────────●────────</b> AFRICA</div></div></section>
<section id="industries" className="section"><div className="intro"><div><p className="eyebrow dark">BUILT AROUND YOUR BUSINESS</p><h2>Logistics for<br/><em>what moves you.</em></h2></div><p>Industry knowledge matters when cargo, timing, compliance and cost all have to work together.</p></div><div className="industryGrid">{industries.map((x,i)=><a href="#contact" key={x}><small>{String(i+1).padStart(2,'0')}</small><b>{x}</b><span>↗</span></a>)}</div></section>
<section id="global-network" className="network"><div className="networkCopy"><p className="eyebrow">GLOBAL REACH · LOCAL EXPERTISE</p><h2>FROM RIYADH<br/><em>TO THE WORLD.</em></h2><p>Strategically positioned in Riyadh with a growing network across the Middle East and Africa, KAS brings regional knowledge to global movement.</p><a className="primary" href="#contact">Our Global Network →</a></div><div className="networkMap"><div className="globe"/><div className="riyadh">● RIYADH</div>{network.map((x,i)=><span className={'node n'+i} key={x}>● {x}</span>)}</div></section>
<section id="about-kas" className="about"><div className="year">2023</div><div><p className="eyebrow dark">KAS FOR LOGISTICS SERVICES</p><h2>Built in Riyadh.<br/><em>Designed for the world.</em></h2><p className="aboutText">KAS is a logistics partner focused on global transportation, GCC e-commerce distribution and industrial solutions across the Middle East and Africa.</p><div className="pillars"><span>01 / Reliability</span><span>02 / Visibility</span><span>03 / Regional Expertise</span><span>04 / Digital Operations</span></div></div></section>
<section id="contact" className="contact"><div><p className="eyebrow">READY TO MOVE?</p><h2>WE MOVE WHAT<br/><span>MOVES THE WORLD.</span></h2></div><div><a className="darkBtn" href="mailto:sales@kaslogistic.com">Start a Conversation →</a><a className="email" href="mailto:sales@kaslogistic.com">sales@kaslogistic.com ↗</a></div></section>
<footer><div className="footTop"><div><img src="/kas-logo.png" alt="KAS"/><p>Global logistics. Regional intelligence.<br/>One partner for every move.</p></div><div className="footCols"><div><b>EXPLORE</b><a href="#services">Services</a><a href="#industries">Industries</a><a href="#global-network">Global Network</a></div><div><b>CONNECT</b><a href="mailto:info@kaslogistic.com">info@kaslogistic.com</a><a href="mailto:sales@kaslogistic.com">sales@kaslogistic.com</a><span>Riyadh, Saudi Arabia</span></div><div><b>FOLLOW</b><span>@KASMena</span><span>KASMena</span></div></div></div><div className="footBottom"><span>© 2026 KAS For Logistics Services</span><span>WE MOVE WHAT MOVES THE WORLD.</span></div></footer>
</main>}
